### ISSUE TITLE
Crashing in v3.0 

### ISSUE THREAD

**Issue by khoren93** [maxep/MXSegmentedPager#48]
Hi, when I dismissed the modal View Controller containing the MXSegmentPager instance, application crashed with the following error.

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x151e9000 of class MXScrollView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x16259d70> (...)'

**Comment by davutklnc** [comment]
I currently had the same issue 

When I implement segmentedpager at a detail page and want to push pop the view it crashes some times at first pop and sometimes at second push. Here is the call stack.

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x14480a600 of class MXScrollView was deallocated while key value observers were still registered with it. Current observation info: NSKeyValueObservationInfo 0x144704da0 (
NSKeyValueObservance 0x14468d180: Observer: 0x144588900, Key path: contentOffset, Options: New: YES, Old: NO, Prior: NO Context: 0x1001e00e8, Property: 0x144553890
NSKeyValueObservance 0x1446dc1b0: Observer: 0x144588900, Key path: contentInset, Options: New: YES, Old: YES, Prior: NO Context: 0x1001e00e8, Property: 0x1446bcc30
)'
**\* First throw call stack:
(0x18475cf48 0x19930ff80 0x18475ce90 0x18561f640 0x199329ae8 0x184640a4c 0x184712068 0x184640ca0 0x18f87c088 0x189d58ffc 0x1000c3fe8 0x199b5e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by maxep** [comment]
Thanks for the report, I will have a look asap. It seems to be an issue in MXParallaxHeader.

**Comment by maxep** [comment]
Can you please try something for me and replace `@property (nonatomic,weak) UIScrollView *scrollView;`by `@property (nonatomic,strong) UIScrollView *scrollView;` in the MXParallaxHeader.m line 27.

**Comment by davutklnc** [comment]
Hello maxep, I didn't test much but replacing weak to strong fixed the crash.

**Comment by khoren93** [comment]
Thanks:)

**Comment by maxep** [comment]
I've released the 3.0.1 with this fix.
