### ISSUE TITLE
UIViewcontroller with tableview inside scrolls oddly when using parallax

### ISSUE THREAD

**Issue by cerupcat** [maxep/MXSegmentedPager#6]
When using parallax, if I create a UIViewController with a tableview inside as one of the pages, the tableview scrolls it's content when scrolling up (before hitting the top).

In the video below, the first page is a regular tableView which works correctly. The 'top' tab is a UIViewController with a tableView inside and displays how the tableView content is scrolling with the outer scrollView incorrectly.

![p9s29mladv](https://cloud.githubusercontent.com/assets/204151/7598658/e14eceee-f8b0-11e4-9d83-f72dd19890e9.gif)

**Comment by maxep** [comment]
Hi @cerupcat,
Yes thats a bug! Do you use a standard UITableViewController or a custom UIViewController with a table view as sub-view?

Thanks!

**Comment by maxep** [comment]
The problem is that the UIViewController's view is not a scrolling-view, so the segmented-pager does not apply a correct behavior to it. The solution would be to specify the correct view that you want to use as a page.

I've applied a correction and you have now two options to get a correct scroll behavior:
- First is setting your table-view (or any scrolling view) as the controller's view :

``` objective-c
- (void)loadView {
    self.view = self.yourTableView;
}
```

By this way, the segmented-pager will see the controller's view as a scrolling-view and will apply the right behavior.
- Second option is using the correction I've just applied. Your view-controller can now adopt the MXPageControllerProtocol protocol which allows you to use a specific view as page. For example: 

``` objective-c
@interface YourViewController () <MXPageControllerProtocol>
@end

@implementation YourViewController
- (UIView *)page {
    return self.yourTableView;
}
@end
```

Your table-view will be used as the page and the right behavior will applied.

Hope this will satisfy your needs.

For standard UITableViewController, UICollectionViewController,... nothing to be done!

Regards,

Maxime.

**Comment by cerupcat** [comment]
That's great, thanks for the quick fix! I'll probably go ahead with the second option for now.

**Comment by cerupcat** [comment]
Can you bump the podspec when you get a chance so that it updates.

**Comment by maxep** [comment]
Yes, I will release a new version soon!

**Comment by maxep** [comment]
Hi @cerupcat 

Sorry I didnt build a new pod yet..
But I have been working on a new solution regarding the parallax header category. The previous approach was not very flexible and accurate. The new one, which is a bit more complex, improves the scrolling effect.
If you have time, could you please try it and tell me if you're facing any regression ?
The tip of the iceberg is the MXPageProtocol, but it's really minor on your side if you use it.

Regards,

Maxime
