### ISSUE TITLE
UISearchController disappears on page index other than 0

### ISSUE THREAD

**Issue by MadeByDouglas** [maxep/MXSegmentedPager#87]
So if a viewController has a UISearch Controller and it is index 0 (the first page in MXSegmentedPager) it works fine, whether you set `self.definesPresentationContext = true` or `false`. 
However, if you set `self.definesPresentationContext = true` and its in another index the search controller disappears when you touch it. 
My workaround is to set `self.definesPresentationContext = false` which works but creates other UI changes as now the searchController affects the other controllers in the stack.

Any ideas?

**Comment by MadeByDouglas** [comment]
I've done more research on this and still nothing. In general, if the search is disappearing when 
`self.definesPresentationContext = true`
people suggest making sure navigation controller bar is translucent or setting `self.extendedLayoutIncludesOpaqueBars =true` however none of these worked. Any ideas?

**Comment by MadeByDouglas** [comment]
video of what i mean https://vimeo.com/179602273

**Comment by crossmetz** [comment]
same problem here , has anyone found a solution yet ?

**Comment by nikae** [comment]
Any solution? I'm having very similar problem.

**Comment by simonbromberg** [comment]
Having same issue. If it's not on the first page the search bar disappears if `definesPresentationContext` is `true` (on the view controller). Need this because otherwise you get weird UI with the search bar floating because the search bar is presented onto the root view controller if nothing else has this flag set to true.

Tried setting it in the container pager controller but it caused the search bar to be vertically offset when activated. Plus it doesn't fix the problem with the search bar staying visible when switching pages.

Also seeing a bunch of these in the console when activating the search bar:

> +[CATransaction synchronize] called within transaction

EDIT:
My *workaround* is just to use a `UISearchBar` directly; Had to do a bit more setup with the cancel buttons and `didBeginEditing`etc but it isn't that much more work.
